### ISSUE TITLE
[Bug] Sending emails at checkout causes significant slowdowns

### ISSUE THREAD

**Issue by BelleNottelling** [FOSSBilling/FOSSBilling#1342]
### Describe the bug

Currently, FOSSBilling sends emails for an order when the checkout is completed which causes a significant multi-second delay between when the user clicks the button and when they are redirected to the service page (2.6 seconds in this example).
I did some simple profiling of the function calls and the delay is entirely caused by the [`send` function](https://github.com/FOSSBilling/FOSSBilling/blob/main/src/library/FOSSBilling/Mail.php#L151) specifically. This function only configures the correct email settings and then sends it, meaning the delay is from the actual send process.

This step needs to be moved so that it's not performed by the same request that's made when the cart is checked out.

Profiling data with the email being sent (Time in milliseconds):
*Note:* The result is not 100% accurate as I somehow messed up the code to call the send function twice, but I removed the time for the duplicated send
```
    functionName: Box\Mod\Cart\Service->createFromCart
    calledFunctions:
        0:
            functionName: Box\Mod\Cart\Service->getSessionCart
            timeElapsed: 0.206481
        1:
            functionName: Box\Mod\Cart\Service->toApiArray
            timeElapsed: 1.869651
        2:
            functionName: Box\Mod\Client\Service->isClientTaxable
            timeElapsed: 0.203001
        3:
            functionName: Box\Mod\Cart\Service->getCartProducts
            timeElapsed: 0.04092
        4:
            functionName: Box\Mod\Order\Service->activateOrder
            calledFunctions:
                0:
                    functionName: Fire onBeforeAdminOrderActivate
                    timeElapsed: 0.428922
                1:
                    functionName: Box\Mod\Order\Service->createFromOrder
                    timeElapsed: 6.167833
                2:
                    functionName: Fire onAfterAdminOrderActivate
                    calledFunctions:
                        0:
                            functionName: Box\Mod\Order\Service->getOrderServiceData
                            timeElapsed: 0.281281
                        1:
                            functionName: Box\Mod\Order\Service->toApiArray
                            timeElapsed: 1.040446
                        2:
                            functionName: Box\Mod\Email\Service->sendTemplate
                            calledFunctions:
                                0:
                                    functionName: FOSSBilling\Mail->send
                                    timeElapsed: 2621.391209
                            timeElapsed: 2630.889821
                    timeElapsed: 2656.816082
                3:
                    functionName: Box\Mod\Order\Service->activateOrderAddons
                    calledFunctions:
                        0:
                            functionName: Box\Mod\Order\Service->getOrderAddonsList
                            timeElapsed: 0.356442
                    timeElapsed: 0.374882
                4:
                    functionName: Log order activation
                    timeElapsed: 1.430808
            timeElapsed: 2665.315528
    timeElapsed: 2672.534407
```

And here's the profiled data when FOSSBilling skips the `send` call:
```
    functionName: Box\Mod\Cart\Service->createFromCart
    calledFunctions:
        0:
            functionName: Box\Mod\Cart\Service->getSessionCart
            timeElapsed: 0.213761
        1:
            functionName: Box\Mod\Cart\Service->toApiArray
            timeElapsed: 2.280932
        2:
            functionName: Box\Mod\Client\Service->isClientTaxable
            timeElapsed: 0.225562
        3:
            functionName: Box\Mod\Cart\Service->getCartProducts
            timeElapsed: 0.04396
        4:
            functionName: Box\Mod\Order\Service->activateOrder
            calledFunctions:
                0:
                    functionName: Fire onBeforeAdminOrderActivate
                    timeElapsed: 0.441083
                1:
                    functionName: Box\Mod\Order\Service->createFromOrder
                    timeElapsed: 6.543276
                2:
                    functionName: Fire onAfterAdminOrderActivate
                    calledFunctions:
                        0:
                            functionName: Box\Mod\Order\Service->getOrderServiceData
                            timeElapsed: 0.279442
                        1:
                            functionName: Box\Mod\Order\Service->toApiArray
                            timeElapsed: 1.116206
                        2:
                            functionName: Box\Mod\Email\Service->sendTemplate
                            timeElapsed: 8.378326
                    timeElapsed: 40.382701
                3:
                    functionName: Box\Mod\Order\Service->activateOrderAddons
                    calledFunctions:
                        0:
                            functionName: Box\Mod\Order\Service->getOrderAddonsList
                            timeElapsed: 0.327121
                    timeElapsed: 0.338521
                4:
                    functionName: Log order activation
                    timeElapsed: 1.332728
            timeElapsed: 49.12443
    timeElapsed: 56.821752
```

So.. yeah. `56.821752` milliseconds if we don't send the email compared to `2672.534407` if we do.

### How to reproduce

Profile the code when completing an order.

### Expected behavior

We should probably move the email task to a queue that's automatically executed by cron, but if we do that we also need to ensure that cron is being configured to run frequently, probably every 5 or so min. Otherwise customers would be stuck waiting quite some time before they receive any emails for their order 

### FOSSBilling version

All
