### ISSUE TITLE
[Bug] SQLSTATE[HY000] [2002]  (trying to connect via (null))

### ISSUE THREAD

**Issue by vasyakrg** [FOSSBilling/FOSSBilling#1663]
### Describe the bug

init billing in docker compose:

```
version: "3.9"
services:
  fossbilling:
    container_name: fossbilling_server
    image: fossbilling/fossbilling
    restart: always
    ports:
      - 8088:80
    volumes:
      - fossbilling:/var/www/html
    networks:
      - net
      - webproxy
    depends_on:
      - mysql

  mysql:
    container_name: fossbilling_db
    image: mysql:8.0.34-debian
    restart: always
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_RANDOM_ROOT_PASSWORD
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - net

volumes:
  fossbilling:
  mysql:

networks:
  net:
  webproxy:
    external: true

```

### How to reproduce

first step - all ok, info page is all green,
second step - i enter all db creds and no error,
third step - i see warning "FOSSBilling installer will create database. It may take some time. Do not close this window. Continue?", 
click Ok and wait, but 3-4 seconds i see error "SQLSTATE[HY000] [2002]  (trying to connect via (null))".

second click on Next generated error: "SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'activity_admin_history' already exists"

if del dir "install" and go to https://ip - i see too "SQLSTATE[HY000] [2002]  (trying to connect via (null))"

### Expected behavior

installed

### FOSSBilling version

0.5.6

### Information

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
Docker version 24.0.6, build ed223bc

**Comment by BelleNottelling** [comment]
Hi @vasyakrg 

Have you tried freshly setting up the docker instance and trying it again?

**Comment by su-haris** [comment]
Hi @BelleNottelling 
I tried just today, fresh reinstall of a VPS with Ubuntu 22.04 and docker.

Below is the compose file I used (referred from documentation)
```
version: "3.9"
services:
  fossbilling:
    image: fossbilling/fossbilling
    restart: always
    ports:
      - 49343:80
    volumes:
      - fossbilling:/var/www/html
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: fossbilling
      MYSQL_USER: fossbillinguser
      MYSQL_PASSWORD: fossbillingpassword
      MYSQL_RANDOM_ROOT_PASSWORD: '123456'
    volumes:
      - mysql:/var/lib/mysql
 
volumes:
  fossbilling:
  mysql:
```

On opening, it first asked to delete the /install directory, which I did on the docker volume.
After that, presented with this screen

![image](https://github.com/FOSSBilling/FOSSBilling/assets/7556250/a2696d66-3e93-42f0-b434-9ec966aa53a2)


Very similar to OP's bug, so did not open a new issue.
