### ISSUE TITLE
[Bug] Docker compose, using local volume folders removes all project files inside of the container

### ISSUE THREAD

**Issue by moda20** [FOSSBilling/FOSSBilling#2064]
### Describe the bug

when using docker compose to run the project, and when using the local volume sync in order to modify some features of the app, the project files inside of the container will be cleared. this issue is not present when using top level volumnes in the compose file. 

here is the example with the issue : 
```
fossbilling:
    image: fossbilling/fossbilling:latest
    restart: always
    ports:
      - 97:80
    volumes:
      - ./fossbilling:/var/www/html
```

here is the documentation compose file example (that works fine, but can't use ti to synchronize files   between host and container)

```
version: "3.9"
services:
  fossbilling:
    image: fossbilling/fossbilling:latest
    restart: always
    ports:
      - 97:80
    volumes:
      - fossbilling:/var/www/html
volumes:
  fossbilling:
```

### How to reproduce

use the above compose files to observe the issue

### Expected behavior

synchronized project files, where the container files will be synchronized to the host to enable easy change

### FOSSBilling version

latest docker image

### Device

Desktop

### Information

macOS 12.1
Chrome for mac
